steps:
  # 1. Build the Docker image
  # Using the full tag here. I've added both :latest and :$COMMIT_SHA
  - name: "gcr.io/cloud-builders/docker"
    id: "Build"
    args: [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${_COMMIT_SHA}",
        "-t",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest",
        ".", # Change this to "./src" ONLY if your Dockerfile is inside the src folder
      ]

  # 2. Deploy to Cloud Run
  # Note: We don't need a "Push" step because the 'images' block below handles it!
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "${_IMAGE_NAME}:${_COMMIT_SHA}",
        "--region",
        "${_REGION}",
        "--platform",
        "managed",
        "--quiet",
      ]

substitutions:
  _REGION: "us-central1"
  _REPO_NAME: "duck-pipeline-artifacts-dev"
  _SERVICE_NAME: "duck-pipeline-service-dev"
  _COMMIT_SHA: "latest" # This will be automatically replaced with the actual commit SHA by Cloud Build
  _IMAGE_NAME: "us-docker.pkg.dev/cloudrun/container/hello" #"duck-pipeline-image"

# This block tells Cloud Build to push these tags automatically after the steps finish
images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${_COMMIT_SHA}"
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest"

options:
  logging: CLOUD_LOGGING_ONLY
